server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /logs/ {
        alias /var/nginx/logs/;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        location ~* \.json$ {
            add_header Content-Type application/json;
            add_header Access-Control-Allow-Origin *;
        }
    }

    location /health {
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
